version: "3"
services:
  backend_api:
    networks:
      - backend
    build:
      context: "."
      dockerfile: "Dockerfile.prod"
    ports:
      - "8001:8001"
  mongo_db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=david
      - MONGO_INITDB_ROOT_PASSWORD=somepassword
    volumes:
      - mongo_db:/data/db
    networks:
      - backend

volumes:
  mongo_db:

networks:
  backend: {}
  
